---
development:
- server: irc.synirc.net
  nick: asterbot-mk2
  channels:
  - ! '#asterbot-staging'
production:
- server: irc.freenode.org
  nick: asterbot
  channels:
  - ! '#csuapad'
  - ! '#redditpad'
- server: irc.synirc.net
  nick: asterbot-mk2
  channels:
  - ! '#zeusisloose'
  - ! '#pad'
